export interface Department {
  id: string;
  slug: string;
  name: string;
  description: string;
  dashboardCount: number;
  accentColor: string;
  borderColor: string;
}

export interface Dashboard {
  id: string;
  name: string;
  description: string;
  department: string;
  lastUpdated: string;
  owner: string;
  tags: string[];
  lookerUrl: string;
}

export interface Metric {
  id: string;
  name: string;
  definition: string;
  category: string;
  source: string;
}

export interface RecentAnswer {
  id: string;
  question: string;
  answer: string;
  source: string;
  timeAgo: string;
}

export const departments: Department[] = [
  {
    id: "legal",
    slug: "legal",
    name: "Legal",
    description: "Compliance tracking, contract SLAs, regulatory filings",
    dashboardCount: 4,
    accentColor: "#4f63d2",
    borderColor: "border-indigo-500",
  },
  {
    id: "customer-support",
    slug: "customer-support",
    name: "Customer Support",
    description: "Ticket volume, resolution times, CSAT scores",
    dashboardCount: 7,
    accentColor: "#06b6d4",
    borderColor: "border-cyan-500",
  },
  {
    id: "office-of-chief-of-staff",
    slug: "office-of-chief-of-staff",
    name: "Office of Chief of Staff",
    description: "OKR progress, headcount, budget, exec reporting",
    dashboardCount: 5,
    accentColor: "#8b5cf6",
    borderColor: "border-violet-500",
  },
  {
    id: "product",
    slug: "product",
    name: "Product",
    description: "Feature adoption, user flows, conversion, A/B tests",
    dashboardCount: 8,
    accentColor: "#a855f7",
    borderColor: "border-purple-500",
  },
  {
    id: "platform",
    slug: "platform",
    name: "Platform",
    description: "Infra health, deploy freq, incidents, SLA monitoring",
    dashboardCount: 6,
    accentColor: "#14b8a6",
    borderColor: "border-teal-500",
  },
  {
    id: "data",
    slug: "data",
    name: "Data",
    description: "Pipeline health, model coverage, data quality, sprint velocity",
    dashboardCount: 9,
    accentColor: "#3b82f6",
    borderColor: "border-blue-500",
  },
];

export const dashboardsByDepartment: Record<string, Dashboard[]> = {
  legal: [
    {
      id: "legal-1",
      name: "Compliance Tracking",
      description: "Real-time view of compliance status across all regulatory frameworks including SOC 2, GDPR, and state campaign finance laws.",
      department: "legal",
      lastUpdated: "2026-05-17",
      owner: "Legal Ops",
      tags: ["Compliance", "Regulatory"],
      lookerUrl: "https://actblue.looker.com/dashboards/legal-compliance",
    },
    {
      id: "legal-2",
      name: "Contract SLA Monitor",
      description: "Tracks all vendor and partner contracts, SLA deadlines, renewal dates, and breach alerts.",
      department: "legal",
      lastUpdated: "2026-05-15",
      owner: "Legal Ops",
      tags: ["Contracts", "SLA"],
      lookerUrl: "https://actblue.looker.com/dashboards/legal-sla",
    },
    {
      id: "legal-3",
      name: "Regulatory Filings Tracker",
      description: "Status of all FEC, state, and local regulatory filings with upcoming deadlines highlighted.",
      department: "legal",
      lastUpdated: "2026-05-14",
      owner: "Compliance Team",
      tags: ["FEC", "Filings", "Regulatory"],
      lookerUrl: "https://actblue.looker.com/dashboards/legal-filings",
    },
    {
      id: "legal-4",
      name: "Audit Log Dashboard",
      description: "Comprehensive audit trail for all system access and data changes for compliance reporting.",
      department: "legal",
      lastUpdated: "2026-05-16",
      owner: "Security & Legal",
      tags: ["Audit", "Access Control"],
      lookerUrl: "https://actblue.looker.com/dashboards/legal-audit",
    },
  ],
  "customer-support": [
    {
      id: "cs-1",
      name: "Ticket Volume Dashboard",
      description: "Daily, weekly, and monthly ticket volumes broken down by category, priority, and channel.",
      department: "customer-support",
      lastUpdated: "2026-05-18",
      owner: "CS Operations",
      tags: ["Tickets", "Volume"],
      lookerUrl: "https://actblue.looker.com/dashboards/cs-volume",
    },
    {
      id: "cs-2",
      name: "Resolution Time Tracker",
      description: "Average and median resolution times by tier, agent, and ticket type with trend analysis.",
      department: "customer-support",
      lastUpdated: "2026-05-17",
      owner: "CS Operations",
      tags: ["Resolution", "SLA"],
      lookerUrl: "https://actblue.looker.com/dashboards/cs-resolution",
    },
    {
      id: "cs-3",
      name: "CSAT Score Dashboard",
      description: "Customer satisfaction scores, NPS trends, verbatim feedback themes, and response rates.",
      department: "customer-support",
      lastUpdated: "2026-05-18",
      owner: "CS Quality",
      tags: ["CSAT", "NPS", "Feedback"],
      lookerUrl: "https://actblue.looker.com/dashboards/cs-csat",
    },
    {
      id: "cs-4",
      name: "Agent Performance Dashboard",
      description: "Per-agent metrics including tickets closed, handle time, CSAT, and queue contributions.",
      department: "customer-support",
      lastUpdated: "2026-05-16",
      owner: "CS Management",
      tags: ["Agents", "Performance"],
      lookerUrl: "https://actblue.looker.com/dashboards/cs-agents",
    },
    {
      id: "cs-5",
      name: "Escalation Rate Monitor",
      description: "Tracks escalation rates by issue type, identifies recurring escalation drivers and resolution paths.",
      department: "customer-support",
      lastUpdated: "2026-05-15",
      owner: "CS Quality",
      tags: ["Escalations"],
      lookerUrl: "https://actblue.looker.com/dashboards/cs-escalations",
    },
    {
      id: "cs-6",
      name: "First Response Time",
      description: "Measures time-to-first-response across channels (email, chat, phone) against SLA targets.",
      department: "customer-support",
      lastUpdated: "2026-05-17",
      owner: "CS Operations",
      tags: ["Response Time", "SLA"],
      lookerUrl: "https://actblue.looker.com/dashboards/cs-frt",
    },
    {
      id: "cs-7",
      name: "Ticket Backlog Dashboard",
      description: "Current backlog size, aging analysis, and projected resolution timelines by priority.",
      department: "customer-support",
      lastUpdated: "2026-05-18",
      owner: "CS Management",
      tags: ["Backlog", "Queue"],
      lookerUrl: "https://actblue.looker.com/dashboards/cs-backlog",
    },
  ],
  "office-of-chief-of-staff": [
    {
      id: "ocs-1",
      name: "OKR Progress Dashboard",
      description: "Company-wide and department-level OKR tracking with progress indicators and risk flags.",
      department: "office-of-chief-of-staff",
      lastUpdated: "2026-05-16",
      owner: "Chief of Staff",
      tags: ["OKRs", "Strategy"],
      lookerUrl: "https://actblue.looker.com/dashboards/ocs-okr",
    },
    {
      id: "ocs-2",
      name: "Headcount Dashboard",
      description: "Current headcount by department, open roles, hiring velocity, and attrition trends.",
      department: "office-of-chief-of-staff",
      lastUpdated: "2026-05-15",
      owner: "People Ops",
      tags: ["Headcount", "Hiring"],
      lookerUrl: "https://actblue.looker.com/dashboards/ocs-headcount",
    },
    {
      id: "ocs-3",
      name: "Budget Tracking",
      description: "Actuals vs. budget by department and cost center with quarterly forecast and variance analysis.",
      department: "office-of-chief-of-staff",
      lastUpdated: "2026-05-14",
      owner: "Finance & CoS",
      tags: ["Budget", "Finance"],
      lookerUrl: "https://actblue.looker.com/dashboards/ocs-budget",
    },
    {
      id: "ocs-4",
      name: "Exec Reporting Dashboard",
      description: "Weekly executive summary covering key business metrics, fundraising health, and operational highlights.",
      department: "office-of-chief-of-staff",
      lastUpdated: "2026-05-18",
      owner: "Chief of Staff",
      tags: ["Exec", "Reporting"],
      lookerUrl: "https://actblue.looker.com/dashboards/ocs-exec",
    },
    {
      id: "ocs-5",
      name: "Strategic Initiatives Tracker",
      description: "Progress and milestone tracking for all cross-functional strategic initiatives.",
      department: "office-of-chief-of-staff",
      lastUpdated: "2026-05-13",
      owner: "Chief of Staff",
      tags: ["Strategy", "Initiatives"],
      lookerUrl: "https://actblue.looker.com/dashboards/ocs-initiatives",
    },
  ],
  product: [
    {
      id: "prod-1",
      name: "Feature Adoption Dashboard",
      description: "Tracks adoption rates for new and existing features by user cohort, geography, and time.",
      department: "product",
      lastUpdated: "2026-05-18",
      owner: "Product Analytics",
      tags: ["Adoption", "Features"],
      lookerUrl: "https://actblue.looker.com/dashboards/prod-adoption",
    },
    {
      id: "prod-2",
      name: "User Flow Analysis",
      description: "Visualizes user journeys through key product flows with drop-off points and conversion funnels.",
      department: "product",
      lastUpdated: "2026-05-17",
      owner: "Product Analytics",
      tags: ["User Flows", "UX"],
      lookerUrl: "https://actblue.looker.com/dashboards/prod-flows",
    },
    {
      id: "prod-3",
      name: "Conversion Rate Dashboard",
      description: "End-to-end donation conversion rates by form type, campaign, and traffic source.",
      department: "product",
      lastUpdated: "2026-05-18",
      owner: "Product Analytics",
      tags: ["Conversion", "Fundraising"],
      lookerUrl: "https://actblue.looker.com/dashboards/prod-conversion",
    },
    {
      id: "prod-4",
      name: "A/B Test Results",
      description: "Live and historical A/B test results with statistical significance, lift estimates, and shipping decisions.",
      department: "product",
      lastUpdated: "2026-05-16",
      owner: "Experimentation",
      tags: ["A/B Tests", "Experimentation"],
      lookerUrl: "https://actblue.looker.com/dashboards/prod-abtests",
    },
    {
      id: "prod-5",
      name: "Retention Dashboard",
      description: "Donor retention cohort analysis by acquisition channel, first gift size, and campaign type.",
      department: "product",
      lastUpdated: "2026-05-15",
      owner: "Product Analytics",
      tags: ["Retention", "Cohorts"],
      lookerUrl: "https://actblue.looker.com/dashboards/prod-retention",
    },
    {
      id: "prod-6",
      name: "Feature Request Tracker",
      description: "Aggregated feature requests from support tickets, NPS responses, and user research.",
      department: "product",
      lastUpdated: "2026-05-12",
      owner: "Product Ops",
      tags: ["Requests", "Roadmap"],
      lookerUrl: "https://actblue.looker.com/dashboards/prod-requests",
    },
    {
      id: "prod-7",
      name: "User Journey Map",
      description: "Cross-channel user journey analysis from first touch to recurring donor.",
      department: "product",
      lastUpdated: "2026-05-14",
      owner: "Product Analytics",
      tags: ["Journey", "Attribution"],
      lookerUrl: "https://actblue.looker.com/dashboards/prod-journey",
    },
    {
      id: "prod-8",
      name: "Funnel Analysis",
      description: "Step-by-step funnel performance for donation checkout with device and browser breakdowns.",
      department: "product",
      lastUpdated: "2026-05-18",
      owner: "Product Analytics",
      tags: ["Funnel", "Checkout"],
      lookerUrl: "https://actblue.looker.com/dashboards/prod-funnel",
    },
  ],
  platform: [
    {
      id: "plat-1",
      name: "Infra Health Dashboard",
      description: "Real-time infrastructure health across all services including CPU, memory, and network utilization.",
      department: "platform",
      lastUpdated: "2026-05-18",
      owner: "Platform Engineering",
      tags: ["Infrastructure", "Health"],
      lookerUrl: "https://actblue.looker.com/dashboards/plat-health",
    },
    {
      id: "plat-2",
      name: "Deploy Frequency Monitor",
      description: "Deployment frequency, success rates, rollback rates, and lead time by team and service.",
      department: "platform",
      lastUpdated: "2026-05-17",
      owner: "Platform Engineering",
      tags: ["Deployments", "DORA"],
      lookerUrl: "https://actblue.looker.com/dashboards/plat-deploys",
    },
    {
      id: "plat-3",
      name: "Incident Tracker",
      description: "Active and historical incidents with MTTR, MTTD, severity distribution, and root cause categories.",
      department: "platform",
      lastUpdated: "2026-05-18",
      owner: "On-Call",
      tags: ["Incidents", "Reliability"],
      lookerUrl: "https://actblue.looker.com/dashboards/plat-incidents",
    },
    {
      id: "plat-4",
      name: "SLA Monitoring Dashboard",
      description: "Uptime and SLA compliance tracking across all external-facing services.",
      department: "platform",
      lastUpdated: "2026-05-17",
      owner: "Platform Engineering",
      tags: ["SLA", "Uptime"],
      lookerUrl: "https://actblue.looker.com/dashboards/plat-sla",
    },
    {
      id: "plat-5",
      name: "Error Rate Dashboard",
      description: "Application error rates by service, endpoint, and error type with alerting thresholds.",
      department: "platform",
      lastUpdated: "2026-05-16",
      owner: "Platform Engineering",
      tags: ["Errors", "Reliability"],
      lookerUrl: "https://actblue.looker.com/dashboards/plat-errors",
    },
    {
      id: "plat-6",
      name: "Latency Dashboard",
      description: "P50/P95/P99 latency metrics by service and endpoint with SLO compliance tracking.",
      department: "platform",
      lastUpdated: "2026-05-18",
      owner: "Platform Engineering",
      tags: ["Latency", "Performance"],
      lookerUrl: "https://actblue.looker.com/dashboards/plat-latency",
    },
  ],
  data: [
    {
      id: "data-1",
      name: "Pipeline Health Dashboard",
      description: "Status of all dbt and Airflow pipelines with failure rates, run durations, and freshness SLAs.",
      department: "data",
      lastUpdated: "2026-05-18",
      owner: "Data Engineering",
      tags: ["Pipelines", "dbt", "Airflow"],
      lookerUrl: "https://actblue.looker.com/dashboards/data-pipelines",
    },
    {
      id: "data-2",
      name: "Model Coverage Dashboard",
      description: "dbt model test coverage, documentation coverage, and schema contract compliance.",
      department: "data",
      lastUpdated: "2026-05-17",
      owner: "Data Engineering",
      tags: ["dbt", "Coverage", "Quality"],
      lookerUrl: "https://actblue.looker.com/dashboards/data-coverage",
    },
    {
      id: "data-3",
      name: "Data Quality Monitor",
      description: "Row count anomaly detection, null rate tracking, and duplicate detection across critical tables.",
      department: "data",
      lastUpdated: "2026-05-18",
      owner: "Data Quality",
      tags: ["Quality", "Anomalies"],
      lookerUrl: "https://actblue.looker.com/dashboards/data-quality",
    },
    {
      id: "data-4",
      name: "Sprint Velocity",
      description: "Data team sprint velocity, story point completion, and cycle time trends.",
      department: "data",
      lastUpdated: "2026-05-16",
      owner: "Data Engineering",
      tags: ["Sprint", "Velocity"],
      lookerUrl: "https://actblue.looker.com/dashboards/data-velocity",
    },
    {
      id: "data-5",
      name: "dbt Model Performance",
      description: "Build times, row counts, and cost per model across all dbt runs in production.",
      department: "data",
      lastUpdated: "2026-05-17",
      owner: "Data Engineering",
      tags: ["dbt", "Performance"],
      lookerUrl: "https://actblue.looker.com/dashboards/data-dbt-perf",
    },
    {
      id: "data-6",
      name: "Data Freshness Tracker",
      description: "SLA compliance for data freshness across all downstream-facing tables and Looker explores.",
      department: "data",
      lastUpdated: "2026-05-18",
      owner: "Data Engineering",
      tags: ["Freshness", "SLA"],
      lookerUrl: "https://actblue.looker.com/dashboards/data-freshness",
    },
    {
      id: "data-7",
      name: "Schema Change Log",
      description: "Historical log of schema changes, breaking changes, and downstream impact assessments.",
      department: "data",
      lastUpdated: "2026-05-14",
      owner: "Data Engineering",
      tags: ["Schema", "Changes"],
      lookerUrl: "https://actblue.looker.com/dashboards/data-schema",
    },
    {
      id: "data-8",
      name: "Coverage Reports",
      description: "Unit test and integration test coverage reports for all data models and transformations.",
      department: "data",
      lastUpdated: "2026-05-15",
      owner: "Data Quality",
      tags: ["Testing", "Coverage"],
      lookerUrl: "https://actblue.looker.com/dashboards/data-test-coverage",
    },
    {
      id: "data-9",
      name: "Data Catalog Usage",
      description: "Tracks which tables, columns, and Looker explores are most queried and by whom.",
      department: "data",
      lastUpdated: "2026-05-18",
      owner: "Data Platform",
      tags: ["Catalog", "Usage"],
      lookerUrl: "https://actblue.looker.com/dashboards/data-catalog",
    },
  ],
};

export const metrics: Metric[] = [
  {
    id: "refund-rate",
    name: "Refund Rate",
    definition: "% of transactions refunded in a period. Excludes chargebacks.",
    category: "Fundraising",
    source: "payments_fact table",
  },
  {
    id: "recurring-donor-rate",
    name: "Recurring Donor Rate",
    definition: "% of unique donors with active recurring pledges. Calculated monthly.",
    category: "Fundraising",
    source: "donors_dim",
  },
  {
    id: "conversion-rate",
    name: "Conversion Rate",
    definition: "% of donation page visitors who complete a transaction.",
    category: "Product",
    source: "events_fact, sessions_fact",
  },
  {
    id: "csat-score",
    name: "CSAT Score",
    definition: "Average customer satisfaction rating (1-5) on resolved support tickets.",
    category: "Customer Support",
    source: "zendesk_tickets_fact",
  },
  {
    id: "first-response-time",
    name: "First Response Time",
    definition: "Median time from ticket creation to first agent reply. Measured in business hours.",
    category: "Customer Support",
    source: "zendesk_tickets_fact",
  },
  {
    id: "donor-ltv",
    name: "Donor Lifetime Value",
    definition: "Total contribution amount per donor from first gift to present, excluding refunds.",
    category: "Fundraising",
    source: "donors_dim, payments_fact",
  },
  {
    id: "deploy-frequency",
    name: "Deploy Frequency",
    definition: "Number of successful production deployments per week per team. DORA metric.",
    category: "Platform",
    source: "deploys_fact",
  },
  {
    id: "pipeline-success-rate",
    name: "Pipeline Success Rate",
    definition: "% of dbt and Airflow pipeline runs completing without failure in a given day.",
    category: "Data",
    source: "pipeline_runs_fact",
  },
  {
    id: "okr-completion-rate",
    name: "OKR Completion Rate",
    definition: "% of key results marked complete at end of quarter. Excludes stretch goals.",
    category: "Strategy",
    source: "okr_tracker (manual)",
  },
  {
    id: "average-gift-size",
    name: "Average Gift Size",
    definition: "Mean transaction amount for a given period, campaign, or donor segment. Excludes refunds.",
    category: "Fundraising",
    source: "payments_fact",
  },
];

export const recentAnswers: RecentAnswer[] = [
  {
    id: "ans-1",
    question: "What was our highest donation day in 2025?",
    answer: "Nov 3, 2025 — $4.2M total. Source: Fundraising Overview dashboard",
    source: "Fundraising Overview dashboard",
    timeAgo: "2h ago",
  },
  {
    id: "ans-2",
    question: "Which state has the highest recurring donor retention?",
    answer: "Vermont — 68% 12-month retention. Source: Donor Retention dashboard",
    source: "Donor Retention dashboard",
    timeAgo: "5h ago",
  },
  {
    id: "ans-3",
    question: "What is our average ticket resolution time this week?",
    answer: "4.2 hours average, down 12% from last week. Source: CS Resolution Time Tracker",
    source: "CS Resolution Time Tracker",
    timeAgo: "1d ago",
  },
  {
    id: "ans-4",
    question: "How many pipelines failed in the last 7 days?",
    answer: "3 pipeline failures detected — all in donations_daily_agg. Source: Pipeline Health Dashboard",
    source: "Pipeline Health Dashboard",
    timeAgo: "2d ago",
  },
];

export const categoryColors: Record<string, string> = {
  Fundraising: "bg-indigo-900/50 text-indigo-300 border border-indigo-700/50",
  Product: "bg-purple-900/50 text-purple-300 border border-purple-700/50",
  "Customer Support": "bg-cyan-900/50 text-cyan-300 border border-cyan-700/50",
  Platform: "bg-teal-900/50 text-teal-300 border border-teal-700/50",
  Data: "bg-blue-900/50 text-blue-300 border border-blue-700/50",
  Strategy: "bg-violet-900/50 text-violet-300 border border-violet-700/50",
};
